const language = {
    'eng': {
        1: "Language",
        2: "Add",
        3: "Delete",
        4: "Search",
        5: "Music Name",
        6: "Genre",
        7: "Action",
        8: "Play",
        9: "Edit",
        10: "Add Song",
        11: "No file chosen",
        12: "Back",
        13: "Enter name's song",
        14: "Song Details",
        15: "Last update",
        16: "Save",
        17: "Total items: ",
        18: "Enter genre's song",
        19: "Selected items: ",
        20: "Login",
        21: "English",
        22: "Please enter your login and password!",
        23: "Username",
        24: "Password",
        25: "Don't have an account?",
        26: "Forgot password?",
        27: "Sign Up",
        28: "Log out",
        29: "Already have account?",
        30: "Confirm password"
        

    },
    'vie': {
        1: "Ngôn ngữ",
        2: "Thêm",
        3: "Xóa",
        4: "Tìm Kiếm",
        5: "Tên bài hát",
        6: "Thể loại",
        7: "Hành động",
        8: "Chơi",
        9: "Sửa",
        10: "Thêm bài hát",
        11: "Không có tệp được chọn",
        12: "Trở lại",
        13: "Nhập tên bài hát",
        14: "Chi tiết bài hát",
        15: "Cập nhật lần cuối",
        16: "Lưu",
        17: "Tổng số bài hát",
        18: "Nhập thể loại bài hát",
        19: "Đã chọn",
        20: "Đăng nhập",
        21: "Tiếng Việt",
        22: "Vui lòng nhập tên đăng nhập và mật khẩu",
        23: "Tên đăng nhập",
        24: "Mật khẩu",
        25: "Chưa có tài khoản?",
        26: "Quên mật khẩu?",
        27: "Đăng ký",
        28: "Đăng xuất",
        29: "Đã có tài khoản",
        30: "Xác nhận mật khẩu"

    },
    'spa': {
        1: "Idioma",
        2: "Agregar",
        3: "Borrar",
        4: "Buscar",
        5: "Nombre de la música",
        6: "Género",
        7: "Acción",
        8: "Jugar",
        9: "Editar",
        10: "Añadir Canción",
        11: "No se ha elegido ningún archivo",
        12: "Atrás",
        13: "Introduzca la canción del nombre",
        14: "Detalles de la canción",
        15: "Última actualización",
        16: "Salvar",
        17: "Total de artículos: ",
        18: "Introduce la canción del género",
        19: "Elementos seleccionados",
        20: "Inicia sesión",
        21: "Español",
        22: "¡Por favor, introduzca su nombre de usuario y contraseña!",
        23: "Nombre de usuario",
        24: "Contraseña",
        25: "¿No tienes una cuenta?",
        26: "¿Olvidó su contraseña?",
        27: "Únete",
        28: "Cerrar sesión",
        29: "¿Ya tienes cuenta?",
        30: "Confirmar contraseña"


    }
}

export default language